#!/usr/bin/env bash
# AmityVox One-Line Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/WAN-Ninjas/AmityVox/main/install.sh | bash
#
# This script clones the repository, generates secure default configuration,
# and starts all services via Docker Compose.

set -euo pipefail

REPO_URL="${AMITYVOX_REPO:-https://github.com/WAN-Ninjas/AmityVox.git}"
INSTALL_DIR="${AMITYVOX_DIR:-$HOME/amityvox}"
BRANCH="${AMITYVOX_BRANCH:-main}"

# Colors for output.
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[AmityVox]${NC} $*"; }
warn() { echo -e "${YELLOW}[AmityVox]${NC} $*"; }
err()  { echo -e "${RED}[AmityVox]${NC} $*" >&2; }

# Check prerequisites.
check_deps() {
    local missing=()
    command -v git    >/dev/null 2>&1 || missing+=(git)
    command -v docker >/dev/null 2>&1 || missing+=(docker)

    if [ ${#missing[@]} -gt 0 ]; then
        err "Missing required tools: ${missing[*]}"
        err "Please install them and try again."
        exit 1
    fi

    # Check Docker Compose (v2 plugin or standalone).
    if docker compose version >/dev/null 2>&1; then
        COMPOSE_CMD="docker compose"
    elif command -v docker-compose >/dev/null 2>&1; then
        COMPOSE_CMD="docker-compose"
    else
        err "Docker Compose is required but not found."
        err "Install it: https://docs.docker.com/compose/install/"
        exit 1
    fi
}

# Generate a random secret string.
gen_secret() {
    openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | base64 | tr -d '/+=' | head -c 64
}

# Clone or update the repository.
setup_repo() {
    if [ -d "$INSTALL_DIR" ]; then
        log "Directory $INSTALL_DIR already exists, pulling latest..."
        cd "$INSTALL_DIR"
        git pull origin "$BRANCH" 2>/dev/null || warn "Could not pull latest changes"
    else
        log "Cloning AmityVox to $INSTALL_DIR..."
        git clone --depth 1 -b "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
        cd "$INSTALL_DIR"
    fi
}

# Generate configuration if it doesn't exist.
setup_config() {
    if [ -f "amityvox.toml" ]; then
        log "Configuration file already exists, skipping generation."
        return
    fi

    log "Generating configuration..."

    local jwt_secret
    jwt_secret=$(gen_secret)
    local db_password
    db_password=$(gen_secret | head -c 32)
    local garage_key
    garage_key=$(gen_secret | head -c 20)
    local garage_secret
    garage_secret=$(gen_secret)
    local meili_key
    meili_key=$(gen_secret | head -c 32)

    cat > amityvox.toml <<TOML
# AmityVox Configuration — generated by install.sh
# Edit this file to customize your instance.

[instance]
name = "AmityVox"
domain = "localhost"

[http]
listen = ":8080"

[database]
url = "postgres://amityvox:${db_password}@postgres:5432/amityvox?sslmode=disable"

[auth]
jwt_secret = "${jwt_secret}"
session_ttl = "720h"

[nats]
url = "nats://nats:4222"

[cache]
url = "redis://dragonfly:6379"

[s3]
endpoint = "garage:3900"
region = "garage"
bucket = "amityvox"
access_key = "${garage_key}"
secret_key = "${garage_secret}"
use_ssl = false

[search]
url = "http://meilisearch:7700"
api_key = "${meili_key}"

[voice]
livekit_url = "ws://livekit:7880"
livekit_api_key = "devkey"
livekit_api_secret = "devsecret"

[giphy]
enabled = false
api_key = ""
TOML

    # Generate a .env file for Docker Compose.
    cat > .env <<ENV
POSTGRES_PASSWORD=${db_password}
MEILI_MASTER_KEY=${meili_key}
GARAGE_ACCESS_KEY=${garage_key}
GARAGE_SECRET_KEY=${garage_secret}
ENV

    log "Configuration generated: amityvox.toml"
    log "Environment file generated: .env"
}

# Build and start services.
start_services() {
    log "Building and starting services..."
    cd deploy/docker

    # Symlink the config and env if needed.
    [ -f "../../amityvox.toml" ] && ln -sf "../../amityvox.toml" ./ 2>/dev/null || true
    [ -f "../../.env" ] && ln -sf "../../.env" ./ 2>/dev/null || true

    $COMPOSE_CMD build --no-cache 2>&1 | tail -5
    $COMPOSE_CMD up -d

    cd ../..
}

# Print completion message.
print_success() {
    echo ""
    log "AmityVox is running!"
    echo ""
    echo "  Web UI:    http://localhost:8080"
    echo "  API:       http://localhost:8080/api/v1"
    echo "  Health:    http://localhost:8080/health"
    echo "  Metrics:   http://localhost:8080/metrics"
    echo ""
    echo "  Config:    $INSTALL_DIR/amityvox.toml"
    echo "  Logs:      cd $INSTALL_DIR/deploy/docker && $COMPOSE_CMD logs -f"
    echo "  Stop:      cd $INSTALL_DIR/deploy/docker && $COMPOSE_CMD down"
    echo ""
    warn "Default configuration uses localhost. Edit amityvox.toml to set your domain."
    warn "Run 'docker compose exec amityvox /amityvox admin create-user' to create an admin."
}

# Main.
main() {
    echo ""
    echo "  ╔═══════════════════════════════╗"
    echo "  ║     AmityVox Installer        ║"
    echo "  ║   Self-hosted communication   ║"
    echo "  ╚═══════════════════════════════╝"
    echo ""

    check_deps
    setup_repo
    setup_config
    start_services
    print_success
}

main "$@"
