ALTER TABLE voice_preferences
  ADD COLUMN IF NOT EXISTS camera_resolution TEXT NOT NULL DEFAULT '720p',
  ADD COLUMN IF NOT EXISTS camera_framerate INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS screenshare_resolution TEXT NOT NULL DEFAULT '1080p',
  ADD COLUMN IF NOT EXISTS screenshare_framerate INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS screenshare_audio BOOLEAN NOT NULL DEFAULT false;
