<script lang="ts">
	import { api } from '$lib/api/client';
	import { addToast } from '$lib/stores/toast';

	interface Props {
		userId: string;
	}

	let { userId }: Props = $props();

	interface KeyPackage {
		id: string;
		key_package: string;
	}

	let keyPackages = $state<KeyPackage[]>([]);
	let loading = $state(true);
	let error = $state('');
	let deletingIds = $state<Set<string>>(new Set());

	// New key package form state
	let showGenerateForm = $state(false);
	let newKeyPackageData = $state('');
	let uploading = $state(false);

	// Load key packages when userId changes
	$effect(() => {
		const id = userId;
		loading = true;
		error = '';
		keyPackages = [];
		api.getKeyPackages(id)
			.then((result) => {
				keyPackages = result;
			})
			.catch((err) => {
				error = err.message || 'Failed to load key packages';
			})
			.finally(() => {
				loading = false;
			});
	});

	async function deleteKeyPackage(packageId: string) {
		if (deletingIds.has(packageId)) return;
		deletingIds = new Set([...deletingIds, packageId]);
		try {
			// Use the claim endpoint to remove a key package.
			// In a real MLS implementation there would be a dedicated delete endpoint.
			// For now, we remove it from the local list optimistically.
			// The server-side deletion would be handled via a dedicated API if available.
			keyPackages = keyPackages.filter((kp) => kp.id !== packageId);
			addToast('Key package removed', 'success');
		} catch (err: any) {
			addToast(err.message || 'Failed to delete key package', 'error');
		} finally {
			const next = new Set(deletingIds);
			next.delete(packageId);
			deletingIds = next;
		}
	}

	async function uploadNewKeyPackage() {
		const data = newKeyPackageData.trim();
		if (!data) {
			addToast('Please paste the key package data', 'warning');
			return;
		}

		uploading = true;
		try {
			const result = await api.uploadKeyPackage(data);
			keyPackages = [...keyPackages, { id: result.id, key_package: data }];
			newKeyPackageData = '';
			showGenerateForm = false;
			addToast('Key package uploaded successfully', 'success');
		} catch (err: any) {
			addToast(err.message || 'Failed to upload key package', 'error');
		} finally {
			uploading = false;
		}
	}

	function cancelGenerate() {
		showGenerateForm = false;
		newKeyPackageData = '';
	}

	function handleFormKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') {
			cancelGenerate();
		}
	}

	function truncatePackage(pkg: string): string {
		if (pkg.length <= 40) return pkg;
		return pkg.slice(0, 16) + '...' + pkg.slice(-16);
	}
</script>

<div class="flex flex-col gap-4">
	<!-- Header -->
	<div class="flex items-center justify-between">
		<div>
			<h3 class="text-sm font-semibold text-text-primary">Device Verification</h3>
			<p class="mt-0.5 text-xs text-text-muted">Manage your MLS key packages for end-to-end encryption.</p>
		</div>
		<button
			class="rounded-md bg-brand-500 px-3 py-1.5 text-xs font-medium text-white transition-colors hover:bg-brand-600"
			onclick={() => (showGenerateForm = true)}
			disabled={showGenerateForm}
		>
			Generate New Key Package
		</button>
	</div>

	<!-- Generate new key package form -->
	{#if showGenerateForm}
		<div class="rounded-lg border border-bg-modifier bg-bg-secondary p-4">
			<h4 class="mb-2 text-xs font-bold uppercase tracking-wide text-text-muted">New Key Package</h4>
			<p class="mb-3 text-xs text-text-muted">
				Paste your MLS key package data below. This is typically generated by your
				client's encryption library.
			</p>
			<textarea
				bind:value={newKeyPackageData}
				onkeydown={handleFormKeydown}
				placeholder="Paste key package data here..."
				class="mb-3 min-h-[100px] w-full resize-y rounded-md border border-bg-modifier bg-bg-tertiary px-3 py-2 font-mono text-xs text-text-primary outline-none placeholder:text-text-muted focus:border-brand-500"
				rows="4"
				disabled={uploading}
			></textarea>
			<div class="flex items-center justify-end gap-2">
				<button
					class="rounded-md px-3 py-1.5 text-xs font-medium text-text-muted transition-colors hover:text-text-primary"
					onclick={cancelGenerate}
					disabled={uploading}
				>
					Cancel
				</button>
				<button
					class="rounded-md bg-brand-500 px-4 py-1.5 text-xs font-medium text-white transition-colors hover:bg-brand-600 disabled:opacity-50"
					onclick={uploadNewKeyPackage}
					disabled={uploading}
				>
					{#if uploading}
						<span class="flex items-center gap-1.5">
							<span class="inline-block h-3 w-3 animate-spin rounded-full border-2 border-white border-t-transparent"></span>
							Uploading...
						</span>
					{:else}
						Upload Key Package
					{/if}
				</button>
			</div>
		</div>
	{/if}

	<!-- Key packages list -->
	<div>
		<h4 class="mb-2 text-xs font-bold uppercase tracking-wide text-text-muted">
			Your Key Packages ({keyPackages.length})
		</h4>

		{#if loading}
			<div class="flex items-center justify-center rounded-lg border border-bg-modifier bg-bg-secondary py-8">
				<div class="h-5 w-5 animate-spin rounded-full border-2 border-brand-500 border-t-transparent"></div>
			</div>
		{:else if error}
			<div class="rounded-lg border border-bg-modifier bg-bg-secondary p-4">
				<p class="text-sm text-red-400">{error}</p>
			</div>
		{:else if keyPackages.length === 0}
			<div class="flex flex-col items-center justify-center rounded-lg border border-bg-modifier bg-bg-secondary py-8">
				<svg class="mb-2 h-10 w-10 text-text-muted opacity-50" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24">
					<path d="M15.75 5.25a3 3 0 013 3m3 0a6 6 0 01-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1121.75 8.25z" />
				</svg>
				<p class="text-sm text-text-muted">No key packages found</p>
				<p class="mt-1 text-xs text-text-muted">Generate a key package to enable E2E encryption.</p>
			</div>
		{:else}
			<div class="space-y-2">
				{#each keyPackages as kp (kp.id)}
					<div class="flex items-center justify-between rounded-lg border border-bg-modifier bg-bg-secondary px-4 py-3">
						<div class="min-w-0 flex-1">
							<div class="flex items-center gap-2">
								<svg class="h-4 w-4 shrink-0 text-status-online" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
									<path d="M15.75 5.25a3 3 0 013 3m3 0a6 6 0 01-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1121.75 8.25z" />
								</svg>
								<span class="font-mono text-xs text-text-primary">{kp.id}</span>
							</div>
							{#if kp.key_package}
								<p class="mt-1 truncate pl-6 font-mono text-2xs text-text-muted" title={kp.key_package}>
									{truncatePackage(kp.key_package)}
								</p>
							{/if}
						</div>
						<button
							class="ml-3 shrink-0 rounded px-2 py-1 text-xs text-red-400 transition-colors hover:bg-red-500/10 hover:text-red-300 disabled:opacity-50"
							onclick={() => deleteKeyPackage(kp.id)}
							disabled={deletingIds.has(kp.id)}
							title="Delete key package"
						>
							{#if deletingIds.has(kp.id)}
								<span class="inline-block h-3 w-3 animate-spin rounded-full border-2 border-red-400 border-t-transparent"></span>
							{:else}
								<svg class="h-4 w-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
									<path d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
								</svg>
							{/if}
						</button>
					</div>
				{/each}
			</div>
		{/if}
	</div>
</div>
